// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.1
//   protoc               v5.28.2
// source: proto/entities.proto

/* eslint-disable */

export const protobufPackage = 'entities'

export interface Empty {}

export interface BankAccEntity {
  id: string
  createdAt: string
  updatedAt: string
  deletedAt: string
  accountNumber: string
  currency: string
  paymentSystem: string
  accountName?: string | undefined
  balance: number
  affiliation: string
  accountType: string
  isBlocked: boolean
  isPremiumAccount: boolean
  isDefaultAccount: boolean
  user: UserEntity | undefined
}

export interface UserEntity {
  id: string
  createdAt: Date
  updatedAt: Date
  deletedAt: Date | null
  userName: string
  userSurname: string
  userLastName: string | null
  email?: string | undefined
  phoneNumber?: string | undefined
  isBlocked: boolean
  accounts: any
}

export const ENTITIES_PACKAGE_NAME = 'entities'
