version: '3.1'

services:
  apigateway:
    container_name: critical-bank-apigateway
    image: ravkdeveloper/critical-bank-apigateway:latest
    volumes:
      - .:/usr/src/app
    env_file:
      - ../envs/apigateway.env
    ports:
      - '3001:3001'
    depends_on:
      - redis
    links:
      - redis
    restart: on-failure
    networks:
      - critical-bank-net
  redis:
    image: redis
    restart: on-failure
    ports:
      - '6379:6379'
    volumes:
      - redis:/data
    env_file:
      - ../envs/apigateway.env
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_URL: ${REDIS_URL}
    networks:
      - critical-bank-net
    hostname: critical-redis
volumes:
  redis:
    driver: local
networks:
  critical-bank-net:
    external: true
