version: '3'

services:
  critical-grafana:
    image: grafana/grafana-enterprise
    container_name: critical-grafana
    restart: unless-stopped
    volumes:
      - critical-grafana:/etc/grafana
    ports:
      - '8134:3000'
    networks:
      - grafana
      - critical-bank-net

  critical-loki:
    image: grafana/loki:2.9.2
    container_name: critical-loki
    ports:
      - '7100:3100'
    volumes:
      - './configs/loki-config.yaml:/etc/loki/local-config.yaml'
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - grafana

  critical-prometheus:
    image: prom/prometheus:latest
    container_name: critical-prometheus
    environment:
      TZ: 'Europe/Moscow'
    restart: unless-stopped
    volumes:
      # - './configs/prometheus.yml:/etc/prometheus/prometheus.yml:ro'
      - 'prometheus_data:/prometheus'
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
    networks:
      - grafana

  critical-node-exporter:
    image: prom/node-exporter
    container_name: critical-node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    hostname: exporter
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.filesystem.ignored-mount-points
      - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
    ports:
      - 9100:9100
    restart: unless-stopped
    environment:
      TZ: 'Europe/Moscow'
    networks:
      - grafana

volumes:
  prometheus_data:
    external: true
  critical-grafana:
    external: true
networks:
  grafana:
    external: true
  critical-bank-net:
    external: true
