version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - critical-bank-net
  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka1
    ports:
      - '9092:9092'
    env_file:
      - ../envs/msg-broker.env
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${KAFKA_EXTERNAL_IP}:9092,PLAINTEXT_HOST://${KAFKA_EXTERNAL_IP}:29092,PLAINTEXT_TEST://kafka1:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,PLAINTEXT_TEST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - critical-bank-net
    volumes:
      - kafka-vol:/var/lib/kafka/data
    depends_on:
      - zookeeper

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8082:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: true
    depends_on:
      - kafka
    networks:
      - critical-bank-net

volumes:
  kafka-vol:
    driver: local
networks:
  critical-bank-net:
    external: true
