global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'apigateway'
    scrape_interval: 5s
    static_configs:
      - targets: ['critical-bank-apigateway:3001']
    metrics_path: /api/metrics
