name: Build apps and deploy to staging

on:
  push:
    branches: ['main']

env:
  DOCKER_IMAGE_NAME: ravkdeveloper/critical-bank-apigateway
  REMOTE_HOST: 5.35.5.106
  REMOTE_PORT: 22
  DEPLOY_DIRECTORY: ~/project/critical-bank
  BUILD_DIRECTORY: ./docker/apigateway.Dockerfile
  REMOTE_USERNAME: root

jobs:
  prepare_envs:
    runs-on: self-hosted
    steps:
      - name: Make envs
        run: echo "sha=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
    outputs:
      sha: ${{ env.sha }}
  build-and-deploy:
    runs-on: self-hosted #ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    needs: [prepare_envs]
    steps:
      - name: 'Cleanup build folder'
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./
      - uses: actions/checkout@v3
      - name: Echo secrets
        run: echo ${{ secrets.DOCKERHUB_USERNAME }} && echo ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Login to Docker Hub
        if: github.event_name == 'push'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        working-directory: ./
        run: docker build . -f ${{ env.BUILD_DIRECTORY }} -t ${{ env.DOCKER_IMAGE_NAME }}:latest

      - name: Push Docker image to Docker Hub
        if: github.event_name == 'push'
        run: docker push ${{ env.DOCKER_IMAGE_NAME }}:latest

      - name: Set up SSH connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.REMOTE_HOST }}
          port: ${{ env.REMOTE_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ env.REMOTE_USERNAME }}

      - name: Pull Docker image on remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.REMOTE_HOST }}
          port: ${{ env.REMOTE_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ env.REMOTE_USERNAME }}
          script: |
            cd ${{ env.DEPLOY_DIRECTORY }}
            docker pull ${{ env.DOCKER_IMAGE_NAME }}:latest

      - name: Stop and remove old container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.REMOTE_HOST }}
          port: ${{ env.REMOTE_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ env.REMOTE_USERNAME }}
          script: |
            cd ${{ env.DEPLOY_DIRECTORY }}
            docker stop critical-bank-apigateway || true
            docker rm critical-bank-apigateway || true

      - name: Run new container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.REMOTE_HOST }}
          port: ${{ env.REMOTE_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ env.REMOTE_USERNAME }}
          script: |
            cd ${{ env.DEPLOY_DIRECTORY }}
            sudo docker-compose -f ./docker/apigateway.docker-compose.yml --env-file ./envs/apigateway.env up -d --build
