name: Build apps and deploy to staging

on:
  push:
    branches: ['main']

env:
  DOCKER_IMAGE_NAME: your-docker-image-name
  REMOTE_HOST: root@5.35.5.106
  REMOTE_PORT: 22
  DEPLOY_DIRECTORY: ~/projects/critical-bank

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        if: github.event_name == 'push'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ env.DOCKER_IMAGE_NAME }}:latest .

      - name: Push Docker image to Docker Hub
        if: github.event_name == 'push'
        run: docker push ${{ env.DOCKER_IMAGE_NAME }}:latest

      - name: Set up SSH connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.REMOTE_HOST }}
          port: ${{ env.REMOTE_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Pull Docker image on remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.REMOTE_HOST }}
          port: ${{ env.REMOTE_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ env.DEPLOY_DIRECTORY }}
            docker pull ${{ env.DOCKER_IMAGE_NAME }}:latest

      - name: Stop and remove old container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.REMOTE_HOST }}
          port: ${{ env.REMOTE_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ env.DEPLOY_DIRECTORY }}
            docker stop critical-bank-apigateway || true
            docker rm critical-bank-apigateway || true

      - name: Run new container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.REMOTE_HOST }}
          port: ${{ env.REMOTE_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ env.DEPLOY_DIRECTORY }}
            sudo docker-compose -f ./docker/apigateway.docker-compose.yml --env-file ./envs/apigateway.env up -d --build
